name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  job_build:
    name: Build
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENABLE_PLATFORM_API: false
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn install

  job_lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: Run Linter
        run: yarn lint

  job_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: Run Tests
        run: yarn test

  job_test_build:
    name: Build (env=test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: Run Tests
        run: yarn build:test

  job_linkcheck:
    name: Test (Linkchecker)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: Install linkcheck
        run: |-
          wget https://github.com/filiph/linkcheck/releases/download/v2.0.12/linkcheck-linux-x64.exe -O ./linkcheck
          chmod +x ./linkcheck
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ./linkcheck
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-linkcheck
      - run: yarn install
      - name: Run linkcheck
        run: |-
          yarn develop > /dev/null &
          printf "Waiting for server to be up"; timeout 60 bash -c 'until $(curl -Isf -o /dev/null "http://localhost:3000"); do printf '.'; sleep 0.5; done'
          ./linkcheck
